let heading = document.createElement("h1");
heading.innerHTML = "Taskify";
let superDiv = document.createElement("div");
superDiv.setAttribute("class", "superDiv");
let TODO = document.createElement("div");
let INPROGRESS = document.createElement("div");
let UNDER_REVIEW = document.createElement("div");
let FINISHED = document.createElement("div");
TODO.innerHTML = "Todo";
INPROGRESS.innerHTML = "In progress";
UNDER_REVIEW.innerHTML = "Under review";
FINISHED.innerHTML = "Finished";
// superDiv.appendChild(heading);
superDiv.appendChild(TODO);
superDiv.appendChild(INPROGRESS);
superDiv.appendChild(UNDER_REVIEW);
superDiv.appendChild(FINISHED);
superDiv.style.display = "flex";
document.body.appendChild(heading);
document.body.appendChild(superDiv);
